matrix:
  include:
    - os: linux
      node_js:
        - 8
        - 6
        - 4
    - os: osx
      osx_image: xcode8.3
      node_js:
        - 8
        - 6
        - 4

language: node_js

before_script:
  - yarn

script:
  - yarn test

cache: yarn
